### PR TITLE
define FastUnicodeData to speedup unicode checks

### PR DESCRIPTION
**Pull request by Alexey-T**

### CODE REVIEW

**Comment by Alexey-T** [comment]
Comparing
before
bench-old-uni

after
bench-new-uni

NOTE- ASCII test- is faster, Uni will be more faster!

**Comment by andgineer** [comment]
project1, unit1?
holiday crossword puzzle? ;)

**Comment by Alexey-T** [comment]
Fixed, renamed project make_unidata files

**Comment by andgineer** [comment]
thank you!

**Pull request merged**
