### PR TITLE
restore MatchIndexFromName(), fix https://github.com/andgineer/TRegEx…

### PR DESCRIPTION
**Pull request by Alexey-T**
…pr/issues/335

### CODE REVIEW

**Comment by Alexey-T** [comment]
@andgineer Pls apply

**Comment by Alexey-T** [comment]
@andgineer Added range-checks - they miss gave the crash in my app in some cases (GetMatchPos with wrong Idx).

**Comment by Alexey-T** [comment]
@andgineer Maybe you can add me to 'collaborators' in repo's settings? so I will be able to commit w/o PR?

**Comment by andgineer** [comment]
of cause just forgot that you still do not have access - thought you asked me for a merge just for an additional check 8-)
try to merge that by yourself - added you to collaborators

**Pull request merged**
