### PR TITLE
Studio fix

### PR DESCRIPTION
**Pull request by mvancanneyt**
If you want, here are the fixes for compiling REStudio under Lazarus and Delphi.
All seems to work.

### CODE REVIEW

**Comment by Alexey-T** [comment]
Only @andgineer can check it(I don't use Studio)

**Comment by Alexey-T** [comment]
@mvancanneyt just a guess. if you add

{$IFDEF FPC}
{$mode delphi}
{$ENDIF}

it will help with `^` issue? then we dont need NODEREF define?

**Comment by mvancanneyt** [comment]
No. 
The in-memory structure of RTTI in FPC is different. This has nothing to do with the mode.
Worse, it will change more in the future. So the define is really needed.

**Comment by mvancanneyt** [comment]
By the way, I just contributed an article to Blaise Pascal magazine: regex for beginners. 
Scheduled to appear in the next issue.

TRegexpr and REStudio for Delphi/lazarus are demonstrated, so perhaps it is a good idea to clean up REStudio a little, so at least it works out of the box. :-)

**Comment by andgineer** [comment]
@Alexey-T 
How do you think about changes in regexpr.pas ?
Is it safe to merge?

**Comment by Alexey-T** [comment]
@andgineer 
This fix conflicts with the current code:
```
uses
  Classes, // TStrings in Split method
  SysUtils, // Exception
  {$IFDEF D2009}
    {$IFDEF D_XE}System.{$ENDIF}Character,
  {$ENDIF}
  Math;
```
so apply, but without regexpr.pas.

**Comment by andgineer** [comment]
Sorry I give up at least for a moment.
I revert regexpr.pas from initial for this PR commit and even squashed commits to have just one change but still github show the same changes as in master as changes in this commit.
I am not sure what will happen after merge so I better won't merge it.
May be we should revert regexpr.pas changes in @mvancanneyt fork - I am not sure.

**Pull request merged**
