### PR TITLE
Add tests for valid/invalid regex sets

### PR DESCRIPTION
**Pull request by SlMaker**

### CODE REVIEW

**Comment by Alexey-T** [comment]
@andgineer don't apply before my pull-req, please. it breaks my pull-req.

**Comment by Alexey-T** [comment]
don't apply. see my comments in issues.

**Comment by andgineer** [comment]
if we want this tests we have to change tests numeration..

**Comment by Alexey-T** [comment]
don't apply. see my comments in issues #146 #147

**Comment by SlMaker** [comment]
superseded by #150

**Pull request closed without merging**
