### PR TITLE
Invalid regex

### PR DESCRIPTION
**Pull request by SlMaker**
#146 which was working in all prior versions but is fixed now

### CODE REVIEW

**Comment by andgineer** [comment]
@SlMaker you can uncomment the test now?

**Comment by SlMaker** [comment]
@andgineer 
the regex should never work as it is not valid at all (but older TRegExpr versions allowed it). Don't know how to test invalid regexes with your testsuite...

**Comment by andgineer** [comment]
invalid re you test exactly as in you PR - TTestRegexpr.TestBadRegex
and in fact last one should raise an exception now..

**Comment by SlMaker** [comment]
Why are the others uncommented then? Should I enable them as well?

**Comment by Alexey-T** [comment]
they are commented. to not raise errors in test project. on testing I temporary enable em.

**Pull request closed without merging**
