### PR TITLE
* Fix compilation for D2009> when no FastUniCodeData is defined

### PR DESCRIPTION
**Pull request by mvancanneyt**
Patch for issue 241 as requested.

### CODE REVIEW

**Comment by Alexey-T** [comment]
@mvancanneyt Pls revert this 
`{ $DEFINE FastUnicodeData} `
because we need FPC version to be run with FastUnicodeData;
or you may add this

{$IFDEF FPC}
{$DEFINE FastUnicodeData}
{$ENDIF}

**Comment by mvancanneyt** [comment]
Pushed as requested

**Comment by Alexey-T** [comment]
@andgineer Pls apply?

**Comment by Alexey-T** [comment]
@mvancanneyt 
`{$IFDEF FPC} // Not supported in FreePascal`
hmm

**Pull request merged**
