### PR TITLE
Docs for recent changes

### PR DESCRIPTION
**Pull request by User4martin**
Added docs.

### CODE REVIEW

**Comment by Alexey-T** [comment]
` (only with AllowBraceWithoutMin)` in regular-expressions.rst. Not suitable IMO. this file tells about the syntax.

**Comment by Alexey-T** [comment]
```
``{,m}``   not more than ``m`` times
``{n,m}``  at least ``n`` but not more than ``m`` times (only with AllowBraceWithoutMin)
```
the braces part is misplaced?

**Comment by User4martin** [comment]
> ` (only with AllowBraceWithoutMin)` in regular-expressions.rst. Not suitable IMO. this file tells about the syntax.

The doc already contains:
```
    Multi-line processing can be tuned by properties
    `LineSeparators <tregexpr.html#lineseparators>`__ and
    `UseLinePairedBreak <tregexpr.html#linepairedseparator>`_.
```

And it affects the Syntax.

**Comment by User4martin** [comment]
> ```
> ``{,m}``   not more than ``m`` times
> ``{n,m}``  at least ``n`` but not more than ``m`` times (only with AllowBraceWithoutMin)
> ```
> 
> the braces part is misplaced?

arghh

**Comment by Alexey-T** [comment]
@andgineer Pls apply.

**Pull request merged**
