### PR TITLE
Allow NULL chars in InputString

### PR DESCRIPTION
**Pull request by Alexey-T**

### CODE REVIEW

**Comment by Alexey-T** [comment]
@andgineer ?

**Comment by andgineer** [comment]
Wow just great!
But don't you think the test is too simple?
I mean you add a lot of changes in different places but the test re is just simple string

**Comment by Alexey-T** [comment]
А что ещё надо сделать в тесте? Нули я тестирую.

**Comment by andgineer** [comment]
Your test do not visit most of this changed code.
Where all this "if" for different cases.

This is because you use just simple sting as re and code for char classes, groups and so on just does not work.

**Comment by Alexey-T** [comment]
How do you suggest to make tests for my code? I don’t understand you

**Comment by andgineer** [comment]
write more complex re

**Comment by Alexey-T** [comment]
Ok, will do it

**Comment by Alexey-T** [comment]
@andgineer Done

**Comment by Alexey-T** [comment]
Note: \x{0} or \x00 don't work in regex, it cannot catch zero char and give ok result.

**Comment by andgineer** [comment]
> Note: \x{0} or \x00 don't work in regex, it cannot catch zero char and give ok result.

Could you explain that - I do not understand, why we cannot use #0 inside regex now, when we do not treat it as string end.

**Comment by Alexey-T** [comment]
- null is not handled in regex, it’s handled only in InputString (maybe later I try to do it in regex)
- why \x00 don’t work in character class- seems this writes null to op code, and later op code is read until null - Emit* functions look like it

**Comment by andgineer** [comment]
thank you for clarification
may be we need ticket for that

**Pull request merged**
