### PR TITLE
Use gbranch in *+ and ?

### PR DESCRIPTION
**Pull request by User4martin**
Since loops use branches (in some cases) let they benefit from the OP_GBRANCH

### CODE REVIEW

**Comment by Alexey-T** [comment]
Can you write in the src, what is the OP_GBRANCH? how it differs from OP_BRANCH?

**Comment by Alexey-T** [comment]
Does it speedup something?

**Comment by User4martin** [comment]
> Does it speedup something?

Yes. gets my current work from 1,25 to 1.20 secs. That's 4%

**Comment by Alexey-T** [comment]
can you decipher the strange comment? -
```
begin // Emit x* as (x&|), where & means "self".
```

**Comment by User4martin** [comment]
Before I make a commit

```
            // To complex for OP_STAR. Write loop using OP_BRANCH
            // 1: loop-content
            // 2: OP_Branch with 2 branches - to allow backtracking
            // 2a: OP_BACK(1) to match the loop again
            // 2b  OP_NOTHING to exit, if the loop can match no more
```

verbose enough?

**Comment by Alexey-T** [comment]
yes. good.

**Comment by Alexey-T** [comment]
what does it mean: `2a: OP_BACK(1)` ?
what is `(1)`.

**Pull request merged**
