### PR TITLE
Support \v and \h, fix testcase for unicode mode

### PR DESCRIPTION
**Pull request by Alexey-T**

### CODE REVIEW

**Comment by Alexey-T** [comment]
@andgineer Tasks with FPC 3.0 had passed ok. Tasks with FPC 2 will never pass- fpc 2.x missed unit "fpwidestring", so please delete fpc 2.x from CI.

**Comment by andgineer** [comment]
You see TRegExpr now IS compatible with fpc 2.
All tests are green.
Why so minor change from you should break it?

**Comment by Alexey-T** [comment]
@andgineer All checks passed now (after my fix to demo code)

**Comment by andgineer** [comment]
Great solution thank you for your patience!

**Pull request merged**
