### PR TITLE
Update RegExpr.pas

### PR DESCRIPTION
**Pull request by dbcto**
Support for Linux64 on Delphi 10.3.

### CODE REVIEW

**Comment by andgineer** [comment]
could you please make tests green for your patch?
the tests run with Free Pascal but $DEF should keep this version good

"Can't find unit UnicodeData used by RegExpr"

**Comment by Alexey-T** [comment]
this patch adds new WideUpperCase/WideLowerCase with LOOONG case operator. not good. better use FPC's widestrringmanager or Delphi's wide funcs.

**Comment by Alexey-T** [comment]
And FPC already has the patch to support WideChar uppercase/ lowercase. so not needed.

**Comment by dbcto** [comment]
> this patch adds new WideUpperCase/WideLowerCase with LOOONG case operator. not good. better use FPC's widestrringmanager or Delphi's wide funcs.

Yes, it's very LOOOONG ;) - but it's 5 times faster than System.SysUtils.UpperCase(Ch1)[1]. And the most important thing is the Linux compatibility for me for Delphi 10.3 which is not given with this implementation: uses
{$IFDEF WIN32}
    Windows; // CharUpper/Lower
{$ELSE}

**Comment by andgineer** [comment]
Thank you!
But could you please fix the code so fpc(lazbuild) tests in travis CI will pass?

**Comment by Alexey-T** [comment]
Please don’t apply this before my big patch

**Comment by dbcto** [comment]
> Thank you!
> But could you please fix the code so fpc(lazbuild) tests in travis CI will pass?

Sorry - I have no fpc to check that and I didn't write the corresponding code in line 730. It seems to be from Alexey Fedorov.

**Comment by andgineer** [comment]
@Alexey-T 
Could you please check if we can incorporate this Delphi change but still have your FPC optimisations?

**Comment by Alexey-T** [comment]
You can close this PR, I will do this change using FPC and Delphi 2009+ Unicode funcs

**Comment by Alexey-T** [comment]
@dbcto See #37 - standard uppercase/lowercase are needed to support all Unicode letters, your patch misses many letters

**Pull request closed without merging**
