### PR TITLE
rework finding chars for char classes [], store to opcode pairs (Kind…

### PR DESCRIPTION
**Pull request by Alexey-T**
…,Data)

### CODE REVIEW

**Comment by andgineer** [comment]
May we have to think about that more?
I am more concerned about additional comparison than the char-type itself.
We have to routinely compare types of each char. Why don't we have just type 'N chars next' and after that we just compare N-times with this chars and do not check type for each of them?

**Comment by Alexey-T** [comment]
It can be optimized such a way (will give little), pls apply patch - I will then cleanup old code of Define UseCharSet, then will do optimization

**Comment by andgineer** [comment]
I used set of chars 
https://www.freepascal.org/docs-html/ref/refsu16.html

for small chars number (less that 26) in hope this is good for performance.

of cause I cannot be sure without load tests.

did you have some reasons to remove that?

**Comment by Alexey-T** [comment]
reason for removing:
- all this TinySet optimization was in the code which emitted null-terminated string, it was conflicting with new opcode (new opcode needs OpKind_Char+Len followed by a string). 
- this TinySet thing was used in NON unicode mode only
- i don't understand that TinySet code so cannot adapt it (it have ~6 variables, some functions)

**Comment by Alexey-T** [comment]
failed CI test -- not my fail, see the report.

**Comment by Alexey-T** [comment]
reason more:

- OP_ANYOFTINYSET cannot handle \w \W \s \S etc in charclasses. OP_ANYOF now can

**Pull request merged**
