### PR TITLE
docs, fix https://github.com/andgineer/TRegExpr/issues/304

### PR DESCRIPTION
**Pull request by Alexey-T**

### CODE REVIEW

**Comment by User4martin** [comment]
Further down in the "boundary" part 
```
Meta-char ``.`` (dot) by default matches any character, but if you
turn **off** the `modifier /s <#s>`_, then it won't match line-breaks inside the string.
```

Also needs to move.

**Comment by Alexey-T** [comment]
Thanks for note, moved now.

**Comment by User4martin** [comment]
Better.... The more I look, the more I find.

The meta-classes in the table below have the note 
```
You may use all meta-classes, mentioned in the table above, within
`user character classes <User Character Classes_>`_.
```
Which does not extend to the "dot", but may be misread.

----

I would
- move the "dot meta" below the "meta classes table"
- Add to the "dot meta"
```
The ``.`` does not act as meta class inside `user character classes <User Character Classes_>`_.
``[.]`` means a literal "."
```

**Comment by Alexey-T** [comment]
'Dot' topic is now separate:

scr

**Comment by User4martin** [comment]
looks ok to me

**Pull request merged**
